export const SESSION_STATE = 'session'

export const SESSION_GET_COCKTAILS = 'session/SESSION_GET_COCKTAILS'
export const SESSION_GET_FILTERS = 'session/SESSION_GET_FILTERS'
export const SESSION_SET_ACTIVE_FILTERS = 'session/SESSION_SET_ACTIVE_FILTERS'
